### ISSUE TITLE
chatterbot 使用中文语料库，报编码错误

### ISSUE THREAD

**Issue by sunchenguang** [wwj718/deepThought#2]
使用win10 python2.7
在代码中设置了编码，但是还是报错。英文是ok的。
bot.py
```
# -*- coding: utf-8 -*-
import sys;reload(sys);sys.setdefaultencoding('utf8')

from chatterbot import ChatBot

chatbot = ChatBot(
    'ABC',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
    silence_performance_warning=True
)

# Train based on the english corpus
chatbot.train("chatterbot.corpus.chinese")

# Get a response to an input statement
response = chatbot.get_response("很高兴认识你")
print(response)
```

运行 `python bot.py`

```
[nltk_data] Downloading package stopwords to                                                     
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...                              
[nltk_data]   Package stopwords is already up-to-date!                                           
[nltk_data] Downloading package wordnet to                                                       
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...                              
[nltk_data]   Package wordnet is already up-to-date!                                             
[nltk_data] Downloading package punkt to                                                         
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...                              
[nltk_data]   Package punkt is already up-to-date!                                               
[nltk_data] Downloading package vader_lexicon to                                                 
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...                              
[nltk_data]   Package vader_lexicon is already up-to-date!                                       
Traceback (most recent call last):                                                               
  File "bot.py", line 13, in <module>                                                            
    chatbot.train("chatterbot.corpus.chinese")                                                   
  File "D:\AnacondaSetup\lib\site-packages\chatterbot\trainers.py", line 117, in train           
    trainer.train(pair)                                                                          
  File "D:\AnacondaSetup\lib\site-packages\chatterbot\trainers.py", line 82, in train            
    statement = self.get_or_create(text)                                                         
  File "D:\AnacondaSetup\lib\site-packages\chatterbot\trainers.py", line 25, in get_or_create    
    statement = self.storage.find(statement_text)                                                
  File "D:\AnacondaSetup\lib\site-packages\chatterbot\storage\jsonfile.py", line 46, in find     
    values = self.database.data(key=statement_text)                                              
  File "D:\AnacondaSetup\lib\site-packages\jsondb\db.py", line 98, in data                       
    return self._get_content(key)                                                                
  File "D:\AnacondaSetup\lib\site-packages\jsondb\db.py", line 52, in _get_content               
    obj = self.read_data(self.path)                                                              
  File "D:\AnacondaSetup\lib\site-packages\jsondb\file_writer.py", line 15, in read_data         
    obj = decode(content)                                                                        
  File "D:\AnacondaSetup\lib\site-packages\jsondb\compat.py", line 28, in decode                 
    return json_decode(value, encoding='utf-8')                                                  
  File "D:\AnacondaSetup\lib\json\__init__.py", line 352, in loads                               
    return cls(encoding=encoding, **kw).decode(s)                                                
  File "D:\AnacondaSetup\lib\json\decoder.py", line 364, in decode                               
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                            
  File "D:\AnacondaSetup\lib\json\decoder.py", line 380, in raw_decode                           
    obj, end = self.scan_once(s, idx)                                                            
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd4 in position 0: invalid continuation byte 

```
不知道是不是有其他因素影响，给官方提了issue回复的人也不清楚什么原因
另外能不能把console前面打出来的[nltk_data]... 隐藏掉，看着好烦  -.-

**Comment by wwj718** [comment]
尽量使用python3吧，如果是python2，目前只支持中文手动训练：`deepThought.train`,不支持预加载语料库

**Comment by sunchenguang** [comment]
好吧~~
